
# Sprint 10

In [110]:
#Libraries used in these Sprint
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import jinja2
import datetime as dt


## Level 1


### Task 1:
##### a. Import the file sprint10.xlsx as a DataFrame. Make sure that the file is imported correctly, with the corresponding column names, without manipulating the original file.
##### b. Sort the DataFrame by country of origin. In case of a tie, sort by city name.
##### c. Show the first 10 rows.
##### d. Additionally, make a printout where you check that the DNI only has unique values.

In [227]:
#a. Import and select name of columns
file_name = "/Users/tonzo/Desktop/IT_ACADEMY/sprint_10/Extra_files/sprint10.xlsx"
#df = pd.read_excel(file_name)
df = pd.read_excel(file_name, header = 3)
#Rename column 0 as Id_num
df.rename( columns={'Unnamed: 0':'Id_num'}, inplace=True )
df.head()

,Id_num,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
0,0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1.144 €,NaN,1.0,Grup B
1,1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1.253 €,1.0,NaN,Grup A
2,2,Fatima,Fassi,38141675A,Marroc,Rabat,6,11,2005,A,1.441 €,1.0,NaN,Grup A
3,3,Khadija,Bennani Bennani,59157262R,Marroc,Rabat,20,1,1995,D,1.944 €,NaN,1.0,Grup B
4,4,Toni,Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1.043 €,NaN,1.0,Grup A

In [228]:
#b. Sort df based on country and city
df = df.sort_values(["País d'origen", "Ciutat"])

In [213]:
#c. the first 10 rows
df.head(n=11)

,Id_num,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
21,21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A
154,154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B
224,224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B
278,278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B
602,602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D
871,871,Lea,Fischer,14773153R,Alemanya,Berlín,9,9,1986,D,1.370 €,1.0,NaN,Grup A
281,281,Lea,Müller,23266650S,Alemanya,Hamburg,14,4,2003,D,1.314 €,NaN,1.0,Grup A
435,435,Anna,Müller,83274277X,Alemanya,Hamburg,1,1,1987,D,2.464 €,NaN,1.0,Grup C
444,444,Laura,Schmidt Müller,60161784X,Alemanya,Hamburg,15,6,1987,NC,2.035 €,1.0,NaN,Grup C
487,487,Lukas,Müller Fischer,60982309S,Alemanya,Hamburg,28,3,1971,H,2.042 €,NaN,1.0,Grup B
546,546,Laura,Schneider,74158500N,Alemanya,Hamburg,25,1,1957,D,1.368 €,NaN,1.0,Grup A

In [229]:
#d. Duplicate values on DNI? F=0, T=1
dup = df.duplicated(subset=["DNI"]).sum()
dup
#Another way would be ton check that the number od Id and the DNI num are unique 
df.nunique()

Id_num               1000
Nom                    80
Cognoms               183
DNI                  1000
País d'origen          10
Ciutat                 26
Dia de Naixement       28
Mes de Naixement       12
Any de Naixement       56
Gènere                  4
Salari mensual        767
Fills                   1
No Fills                1
Grup Professional       4
dtype: int64

### Task 2:
##### a. Create a column that is the full name.
##### b. Create a column if the person was born in Spain or not.
##### c. Put the DNI as the index of the DataFrame (row names).
##### d. Replace the name of the columns Day of Birth, Month of Birth and Year of Birth with Day, Month and Year.
##### e. Replace H with Male, D with Female, A with Others and NC with a missing data (nan/null/na).
##### f. Show all the changes you have made in a single table.

In [230]:
#a. Create a column full name 
df["Full Name"] = df["Nom"].astype(str) + " " + df["Cognoms"].astype(str)
df

,Id_num,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Full Name
21,21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A,Mia Schneider Fischer
154,154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B,Laura Schneider Fischer
224,224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B,Lea Schneider Schneider
278,278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B,Mia Fischer
602,602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D,Jonas Schneider
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,547,Emily,Taylor Jones,89577876S,Regne Unit,Manchester,28,3,1958,D,2.033 €,NaN,1.0,Grup B,Emily Taylor Jones
728,728,George,Brown Jones,57441590Y,Regne Unit,Manchester,27,12,1979,H,1.130 €,1.0,NaN,Grup A,George Brown Jones
751,751,Olivia,Brown Brown,58204038A,Regne Unit,Manchester,28,8,1952,A,1.023 €,NaN,1.0,Grup A,Olivia Brown Brown
854,854,Isla,Jones Brown,28367234K,Regne Unit,Manchester,28,3,1999,D,1.197 €,NaN,1.0,Grup A,Isla Jones Brown
872,872,William,Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1.405 €,1.0,NaN,Grup A,William Smith

In [231]:
#b.
def spain(country):
    if country["País d'origen"]  == "Spain":
        return "Yes"
    else:
        return "Non"
df["Spanish"] = df.apply(spain, axis = 1)
df

,Id_num,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Full Name,Spanish
21,21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A,Mia Schneider Fischer,Non
154,154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B,Laura Schneider Fischer,Non
224,224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B,Lea Schneider Schneider,Non
278,278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B,Mia Fischer,Non
602,602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D,Jonas Schneider,Non
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,547,Emily,Taylor Jones,89577876S,Regne Unit,Manchester,28,3,1958,D,2.033 €,NaN,1.0,Grup B,Emily Taylor Jones,Non
728,728,George,Brown Jones,57441590Y,Regne Unit,Manchester,27,12,1979,H,1.130 €,1.0,NaN,Grup A,George Brown Jones,Non
751,751,Olivia,Brown Brown,58204038A,Regne Unit,Manchester,28,8,1952,A,1.023 €,NaN,1.0,Grup A,Olivia Brown Brown,Non
854,854,Isla,Jones Brown,28367234K,Regne Unit,Manchester,28,3,1999,D,1.197 €,NaN,1.0,Grup A,Isla Jones Brown,Non
872,872,William,Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1.405 €,1.0,NaN,Grup A,William Smith,Non

In [232]:
#c. DNI as index
df = df.set_index("DNI")
df

,Id_num,Nom,Cognoms,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Full Name,Spanish
DNI,,,,,,,,,,,,,,,
28973553Z,21,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A,Mia Schneider Fischer,Non
37399141L,154,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B,Laura Schneider Fischer,Non
37368317L,224,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B,Lea Schneider Schneider,Non
21390098Z,278,Mia,Fischer,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B,Mia Fischer,Non
44060014R,602,Jonas,Schneider,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D,Jonas Schneider,Non
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,547,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,D,2.033 €,NaN,1.0,Grup B,Emily Taylor Jones,Non
57441590Y,728,George,Brown Jones,Regne Unit,Manchester,27,12,1979,H,1.130 €,1.0,NaN,Grup A,George Brown Jones,Non
58204038A,751,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,A,1.023 €,NaN,1.0,Grup A,Olivia Brown Brown,Non
28367234K,854,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,D,1.197 €,NaN,1.0,Grup A,Isla Jones Brown,Non
82046699J,872,William,Smith,Regne Unit,Manchester,19,5,1997,H,1.405 €,1.0,NaN,Grup A,William Smith,Non

In [233]:
#d. rename columns
df.rename(columns={'Dia de Naixement':'Day', 'Mes de Naixement':'Month', 'Any de Naixement':'Year'}, inplace=True )
df

,Id_num,Nom,Cognoms,País d'origen,Ciutat,Day,Month,Year,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Full Name,Spanish
DNI,,,,,,,,,,,,,,,
28973553Z,21,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A,Mia Schneider Fischer,Non
37399141L,154,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B,Laura Schneider Fischer,Non
37368317L,224,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B,Lea Schneider Schneider,Non
21390098Z,278,Mia,Fischer,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B,Mia Fischer,Non
44060014R,602,Jonas,Schneider,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D,Jonas Schneider,Non
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,547,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,D,2.033 €,NaN,1.0,Grup B,Emily Taylor Jones,Non
57441590Y,728,George,Brown Jones,Regne Unit,Manchester,27,12,1979,H,1.130 €,1.0,NaN,Grup A,George Brown Jones,Non
58204038A,751,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,A,1.023 €,NaN,1.0,Grup A,Olivia Brown Brown,Non
28367234K,854,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,D,1.197 €,NaN,1.0,Grup A,Isla Jones Brown,Non
82046699J,872,William,Smith,Regne Unit,Manchester,19,5,1997,H,1.405 €,1.0,NaN,Grup A,William Smith,Non

In [234]:
#b.
def replace(gender):
    if gender["Gènere"]  == "D":
        return "Woman"
    elif gender["Gènere"]  == "H":
        return "Man"
    elif gender["Gènere"]  == "A":
        return "Others"
    else:
        return "NaN"
df["Gènere"] = df.apply(replace, axis = 1)
df

,Id_num,Nom,Cognoms,País d'origen,Ciutat,Day,Month,Year,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Full Name,Spanish
DNI,,,,,,,,,,,,,,,
28973553Z,21,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Others,951 €,NaN,1.0,Grup A,Mia Schneider Fischer,Non
37399141L,154,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Woman,1.769 €,1.0,NaN,Grup B,Laura Schneider Fischer,Non
37368317L,224,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Woman,2.013 €,NaN,1.0,Grup B,Lea Schneider Schneider,Non
21390098Z,278,Mia,Fischer,Alemanya,Berlín,11,8,1950,Woman,1.557 €,1.0,NaN,Grup B,Mia Fischer,Non
44060014R,602,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Man,2.754 €,1.0,NaN,Grup D,Jonas Schneider,Non
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,547,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Woman,2.033 €,NaN,1.0,Grup B,Emily Taylor Jones,Non
57441590Y,728,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Man,1.130 €,1.0,NaN,Grup A,George Brown Jones,Non
58204038A,751,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Others,1.023 €,NaN,1.0,Grup A,Olivia Brown Brown,Non
28367234K,854,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Woman,1.197 €,NaN,1.0,Grup A,Isla Jones Brown,Non
82046699J,872,William,Smith,Regne Unit,Manchester,19,5,1997,Man,1.405 €,1.0,NaN,Grup A,William Smith,Non

### Task 3:
##### a. Merge the Children and Not Children columns into a single column, using the .apply() method and defining a function that solves the problem. The new column should be called "Children" and take the values ​​"Yes" or "No".

In [235]:
#Creamos funcion con apply y generamos nueva columna "Children" en base a procesado de "Fills" y "No Fills"
def fills(user):
    if user["Fills"]  == 1.0:
        return "Yes"
    elif user["No Fills"] == 1.0:
        return "No"
    else:
        return "None"
df['Children'] = df.apply(fills, axis = 1)
df

,Id_num,Nom,Cognoms,País d'origen,Ciutat,Day,Month,Year,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Full Name,Spanish,Children
DNI,,,,,,,,,,,,,,,,
28973553Z,21,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Others,951 €,NaN,1.0,Grup A,Mia Schneider Fischer,Non,No
37399141L,154,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Woman,1.769 €,1.0,NaN,Grup B,Laura Schneider Fischer,Non,Yes
37368317L,224,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Woman,2.013 €,NaN,1.0,Grup B,Lea Schneider Schneider,Non,No
21390098Z,278,Mia,Fischer,Alemanya,Berlín,11,8,1950,Woman,1.557 €,1.0,NaN,Grup B,Mia Fischer,Non,Yes
44060014R,602,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Man,2.754 €,1.0,NaN,Grup D,Jonas Schneider,Non,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,547,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Woman,2.033 €,NaN,1.0,Grup B,Emily Taylor Jones,Non,No
57441590Y,728,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Man,1.130 €,1.0,NaN,Grup A,George Brown Jones,Non,Yes
58204038A,751,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Others,1.023 €,NaN,1.0,Grup A,Olivia Brown Brown,Non,No
28367234K,854,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Woman,1.197 €,NaN,1.0,Grup A,Isla Jones Brown,Non,No
82046699J,872,William,Smith,Regne Unit,Manchester,19,5,1997,Man,1.405 €,1.0,NaN,Grup A,William Smith,Non,Yes

### Task 4:
##### a. Create a summary table that allows you to see the average, median, minimum and maximum salary by Gender.
##### b. Sort the table based on average salary.

In [236]:
#a. summary table
#Primero eliminamos simbolos de esta columna
df["Salari mensual"] = df["Salari mensual"].replace(r'[^\d.]', '', regex=True)
#Transformamos los valores de la columna en numeros
df["Salari mensual"] = pd.to_numeric(df["Salari mensual"], errors='coerce')
#df.groupby("Gènere")["Salari mensual"].describe() y bajamos a 2 decimales
salary = df.groupby("Gènere")["Salari mensual"].agg(['mean', 'median', 'min', 'max']).round(2)
#b. Ordenamos por la columna mean de mayor a menor
salary_desc = salary.sort_values(by="mean", ascending=False)
salary_desc

          mean  median   min    max
Gènere
Woman   162.23    1.63  1.00  999.0
Others  132.22    1.82  1.02  996.0
NaN     117.20    1.59  1.01  974.0
Man      98.33    1.67  1.00  997.0

### Task 5:
##### a. Create a summary table with the average salary by gender (rows) and country of origin (columns).

##### b. Add the averages to the table margins.

##### c. (EXTRA): Apply conditional formatting to the table to see the highest values ​​in a more intense color

In [237]:
#a y b.
pivot_table = df.pivot_table(
    values="Salari mensual", 
    index="Gènere", 
    columns="País d'origen", 
    aggfunc='mean', 
    margins=True, 
    margins_name='Total (Average)'
)
round_table = pivot_table.round(2)
round_table

País d'origen,Alemanya,Argentina,Colòmbia,Espanya,França,Itàlia,Marroc,Mèxic,Portugal,Regne Unit,Total (Average)
Gènere,,,,,,,,,,,
Man,2.07,106.54,109.98,93.66,207.18,119.06,178.85,1.62,1.50,212.95,98.33
NaN,1.93,253.55,1.25,101.87,1.57,1.32,1.37,1.58,468.84,1.76,117.20
Others,951.00,1.14,498.53,140.39,NaN,1.42,1.36,1.37,1.76,1.92,132.22
Woman,60.67,245.15,184.26,173.38,146.60,162.81,62.34,151.07,150.43,54.05,162.23
Total (Average),76.44,162.08,166.67,130.84,177.77,119.52,92.01,82.40,114.67,97.35,129.31

In [238]:
#c. 
styled_table = round_table.style.background_gradient(cmap='YlGnBu', axis=None).format(precision=2)
styled_table

### Task 6:
##### a. Create a new column that is the date of birth in Datetime format from the day, month, and year columns. 
##### b. Using this column, create a function that, given a date, calculates your current age as of today.
##### c. Use the function you just created to generate a new column in the DataFrame with the current age.

In [239]:
#a. 
df["Date_of_birth"] = pd.to_datetime(df[["Year", "Month", "Day"]].rename(columns={
    "Year": "year",
    "Month": "month",
    "Day": "day"
}))
df

,Id_num,Nom,Cognoms,País d'origen,Ciutat,Day,Month,Year,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Full Name,Spanish,Children,Date_of_birth
DNI,,,,,,,,,,,,,,,,,
28973553Z,21,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Others,951.000,NaN,1.0,Grup A,Mia Schneider Fischer,Non,No,1976-10-22
37399141L,154,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Woman,1.769,1.0,NaN,Grup B,Laura Schneider Fischer,Non,Yes,1958-02-02
37368317L,224,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Woman,2.013,NaN,1.0,Grup B,Lea Schneider Schneider,Non,No,2005-10-23
21390098Z,278,Mia,Fischer,Alemanya,Berlín,11,8,1950,Woman,1.557,1.0,NaN,Grup B,Mia Fischer,Non,Yes,1950-08-11
44060014R,602,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Man,2.754,1.0,NaN,Grup D,Jonas Schneider,Non,Yes,1985-11-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,547,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Woman,2.033,NaN,1.0,Grup B,Emily Taylor Jones,Non,No,1958-03-28
57441590Y,728,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Man,1.130,1.0,NaN,Grup A,George Brown Jones,Non,Yes,1979-12-27
58204038A,751,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Others,1.023,NaN,1.0,Grup A,Olivia Brown Brown,Non,No,1952-08-28
28367234K,854,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Woman,1.197,NaN,1.0,Grup A,Isla Jones Brown,Non,No,1999-03-28
82046699J,872,William,Smith,Regne Unit,Manchester,19,5,1997,Man,1.405,1.0,NaN,Grup A,William Smith,Non,Yes,1997-05-19

In [240]:
#b. Generamos la funcion para calcular la edad en base a la fecha de nacimiento
from datetime import date

def calculateAge(birthDate):
    today = date.today()
    age = today.year - birthDate.year - ((today.month, today.day) < (birthDate.month, birthDate.day))
    return age

#print(calculateAge(date((1997, 2, 3)), "Years"))

#c.  Aplicamos la función a cada fila de la columna
df["Age"] = df["Date_of_birth"].apply(calculateAge)
df

,Id_num,Nom,Cognoms,País d'origen,Ciutat,Day,Month,Year,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Full Name,Spanish,Children,Date_of_birth,Age
DNI,,,,,,,,,,,,,,,,,,
28973553Z,21,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Others,951.000,NaN,1.0,Grup A,Mia Schneider Fischer,Non,No,1976-10-22,49
37399141L,154,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Woman,1.769,1.0,NaN,Grup B,Laura Schneider Fischer,Non,Yes,1958-02-02,68
37368317L,224,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Woman,2.013,NaN,1.0,Grup B,Lea Schneider Schneider,Non,No,2005-10-23,20
21390098Z,278,Mia,Fischer,Alemanya,Berlín,11,8,1950,Woman,1.557,1.0,NaN,Grup B,Mia Fischer,Non,Yes,1950-08-11,75
44060014R,602,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Man,2.754,1.0,NaN,Grup D,Jonas Schneider,Non,Yes,1985-11-22,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,547,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Woman,2.033,NaN,1.0,Grup B,Emily Taylor Jones,Non,No,1958-03-28,68
57441590Y,728,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Man,1.130,1.0,NaN,Grup A,George Brown Jones,Non,Yes,1979-12-27,46
58204038A,751,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Others,1.023,NaN,1.0,Grup A,Olivia Brown Brown,Non,No,1952-08-28,73
28367234K,854,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Woman,1.197,NaN,1.0,Grup A,Isla Jones Brown,Non,No,1999-03-28,27
82046699J,872,William,Smith,Regne Unit,Manchester,19,5,1997,Man,1.405,1.0,NaN,Grup A,William Smith,Non,Yes,1997-05-19,28


## Level 2

### Task 1:
##### a. Using the following DataFrame, attach the "Increment" column to the dataframe of the previous level.
##### b. Update the salary column based on the percentages attached. Do not manually modify the increments, write Python code for the necessary conversions.

In [241]:
#a.:
df_increment = pd.DataFrame({"Grup":["Grup A","Grup B","Grup C", "Grup D" ] , "Increment":
["5%","3,5%","2%","8%"]})
df_increment

     Grup Increment
0  Grup A        5%
1  Grup B      3,5%
2  Grup C        2%
3  Grup D        8%

In [245]:
new_df = pd.merge(
    left=df, 
    right=df_increment,
    how='left',
    left_on=["Grup Professional"],
    right_on=["Grup"],
)
#new_df.dtypes
# Assuming 'df' is your DataFrame and 'column_name' is the target
new_df['Increment'] = new_df['Increment'].str.replace('%', '', regex=False)
new_df['Increment'] = new_df['Increment'].str.replace(',', '.', regex=False)
new_df

,Id_num,Nom,Cognoms,País d'origen,Ciutat,Day,Month,Year,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Full Name,Spanish,Children,Date_of_birth,Age,Grup,Increment
0,21,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Others,951.000,NaN,1.0,Grup A,Mia Schneider Fischer,Non,No,1976-10-22,49,Grup A,5
1,154,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Woman,1.769,1.0,NaN,Grup B,Laura Schneider Fischer,Non,Yes,1958-02-02,68,Grup B,3.5
2,224,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Woman,2.013,NaN,1.0,Grup B,Lea Schneider Schneider,Non,No,2005-10-23,20,Grup B,3.5
3,278,Mia,Fischer,Alemanya,Berlín,11,8,1950,Woman,1.557,1.0,NaN,Grup B,Mia Fischer,Non,Yes,1950-08-11,75,Grup B,3.5
4,602,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Man,2.754,1.0,NaN,Grup D,Jonas Schneider,Non,Yes,1985-11-22,40,Grup D,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,547,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Woman,2.033,NaN,1.0,Grup B,Emily Taylor Jones,Non,No,1958-03-28,68,Grup B,3.5
996,728,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Man,1.130,1.0,NaN,Grup A,George Brown Jones,Non,Yes,1979-12-27,46,Grup A,5
997,751,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Others,1.023,NaN,1.0,Grup A,Olivia Brown Brown,Non,No,1952-08-28,73,Grup A,5
998,854,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Woman,1.197,NaN,1.0,Grup A,Isla Jones Brown,Non,No,1999-03-28,27,Grup A,5
999,872,William,Smith,Regne Unit,Manchester,19,5,1997,Man,1.405,1.0,NaN,Grup A,William Smith,Non,Yes,1997-05-19,28,Grup A,5

In [246]:
new_df['Increment'] = new_df['Increment'].astype(float)
new_df.dtypes

Id_num                        int64
Nom                          object
Cognoms                      object
País d'origen                object
Ciutat                       object
Day                           int64
Month                         int64
Year                          int64
Gènere                       object
Salari mensual              float64
Fills                       float64
No Fills                    float64
Grup Professional            object
Full Name                    object
Spanish                      object
Children                     object
Date_of_birth        datetime64[ns]
Age                           int64
Grup                         object
Increment                   float64
dtype: object

In [257]:
#b. Calculamos un nuevo salario en base al % de incremento
new_df["New_salary"] = ((new_df["Salari mensual"] * new_df["Increment"])/100 + new_df["Salari mensual"]).round(2)
new_df

,Id_num,Nom,Cognoms,País d'origen,Ciutat,Day,Month,Year,Gènere,Salari mensual,...,No Fills,Grup Professional,Full Name,Spanish,Children,Date_of_birth,Age,Grup,Increment,New_salary
0,21,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Others,951.000,...,1.0,Grup A,Mia Schneider Fischer,Non,No,1976-10-22,49,Grup A,5.0,998.55
1,154,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Woman,1.769,...,NaN,Grup B,Laura Schneider Fischer,Non,Yes,1958-02-02,68,Grup B,3.5,1.83
2,224,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Woman,2.013,...,1.0,Grup B,Lea Schneider Schneider,Non,No,2005-10-23,20,Grup B,3.5,2.08
3,278,Mia,Fischer,Alemanya,Berlín,11,8,1950,Woman,1.557,...,NaN,Grup B,Mia Fischer,Non,Yes,1950-08-11,75,Grup B,3.5,1.61
4,602,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Man,2.754,...,NaN,Grup D,Jonas Schneider,Non,Yes,1985-11-22,40,Grup D,8.0,2.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,547,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Woman,2.033,...,1.0,Grup B,Emily Taylor Jones,Non,No,1958-03-28,68,Grup B,3.5,2.10
996,728,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Man,1.130,...,NaN,Grup A,George Brown Jones,Non,Yes,1979-12-27,46,Grup A,5.0,1.19
997,751,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Others,1.023,...,1.0,Grup A,Olivia Brown Brown,Non,No,1952-08-28,73,Grup A,5.0,1.07
998,854,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Woman,1.197,...,1.0,Grup A,Isla Jones Brown,Non,No,1999-03-28,27,Grup A,5.0,1.26
999,872,William,Smith,Regne Unit,Manchester,19,5,1997,Man,1.405,...,NaN,Grup A,William Smith,Non,Yes,1997-05-19,28,Grup A,5.0,1.48

### Task 2:
##### a. Using a loop, export the data of each Grup Professional in 4 files (.xlsx or .csv format).
##### For example: "dades_GrupA.xlsx" , "dades_GrupB.xlsx" ...
##### b. Exports a 5è DataFrame in .xlsx or .csv format that contains how many workers there are for each Grup Professional, who is the most middle-aged.

In [258]:
#a. We export each professional group in 4 formats
groups = new_df["Grup Professional"].unique()

for g in groups:
    # Filter the DataFrame for the specific group
    df_grup = new_df[new_df["Grup Professional"] == g]
    
    # Create the filename dynamically
    filename = f"dades_{g}.csv"
    
    # Export to Excel
    df_grup.to_csv(filename, index=False)

##### Se han generado los sigueintes archivos:
###### -rw-r--r--@ 1 tonzo  staff    53K Apr 23 11:24 dades_Grup A.csv
###### -rw-r--r--@ 1 tonzo  staff    35K Apr 23 11:24 dades_Grup B.csv
###### -rw-r--r--@ 1 tonzo  staff   6.1K Apr 23 11:24 dades_Grup D.csv
###### -rw-r--r--@ 1 tonzo  staff    15K Apr 23 11:24 dades_Grup C.csv
###### -rw-r--r--@ 1 tonzo  staff   175K Apr 23 11:24 sprint_10.ipynb

In [259]:
# 1. Number of workers per group
summary = new_df.groupby("Grup Professional").size().reset_index(name="Worker Count")
summary

  Grup Professional  Worker Count
0            Grup A           490
1            Grup B           318
2            Grup C           137
3            Grup D            55

In [270]:
# 2.
# Agrupació de dades per Grup Professional
resum_df = new_df.groupby("Grup Professional").agg({"Grup Professional": "count", "New_salary": "mean", "Age": "median"}).rename(columns={"Grup Professional": "Worker_Count"}).reset_index().round(2)
#resum_df
# Exportació del 5è DataFrame
resum_df.to_csv("resum_Professional_groups.csv", index=False)